Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "puppet/scripts/bootstrap.sh"

  # ip configuration. Also, make sure this is in sync with puppet/hieradata/*
  node_ex_ip = "192.168.0.254"

  config.vm.provision "shell", path: "puppet/scripts/base1.sh"
  config.vm.provision "puppet" do |puppet|
      puppet.hiera_config_path = "puppet/hiera.yaml"
      puppet.working_directory = "/vagrant/puppet"
      puppet.manifests_path = "puppet/manifests"
      puppet.module_path = "puppet/modules"
      puppet.manifest_file  = "base2.pp"
  end

  # During initial provisioning we expect yum update to get a new kernel. Because of that, we
  # will be required to reboot the vm. If you rather do that manually, simply comment out provision line below.
  # Otherwise, simply install the reload plugin in vagrant:  vagrant plugin install vagrant-reload
  config.vm.provision :reload

  config.vm.define "router-node" do |config|
    config.vm.box = "bento/centos-6.7"
    config.vm.hostname = "router-node"
    config.vm.network "private_network", ip: "#{node_ex_ip}"
    #config.vm.network "private_network", ip: "#{node_ex_ip}", virtualbox__intnet: "mylocalnet", auto_config: true
    # http://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "128"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      #vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      #vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      #vb.customize ["modifyvm", :id, "--macaddress2", "00005E000101"]
    end
  end

end
